# Generated by Django 4.1 on 2022-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.PositiveIntegerField()),
                ('sepal_width', models.PositiveIntegerField()),
                ('petal_length', models.PositiveIntegerField()),
                ('petal_width', models.PositiveIntegerField()),
            ],
        ),
    ]
