# Generated by Django 4.1 on 2022-08-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irisApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Predict',
        ),
    ]
